name: Run API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
# Проблема была в модуле allure но я для истории оставлю - полезный код с крутым логированием в случае ошибки
    steps:
      - uses: actions/checkout@v4

      - name: Show current directory
        run: pwd

      - name: Show files in current directory
        run: ls -la

      - name: Show files in .github/workflows
        run: ls -la .github/workflows

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest pytest-html requests allure-pytest

      - name: Start FastAPI Server
        run: |
          nohup uvicorn main:app --host 127.0.0.1 --port 3000 > server.log 2>&1 &
          sleep 10
          cat server.log
          for i in {1..30}; do
            if curl --fail http://127.0.0.1:3000/glucose; then
              echo "Server is up!"
              exit 0
            fi
            echo "Waiting for server..."
            sleep 1
          done
          echo "Server did not start in time."
          exit 1

      - name: Output server logs on failure
        if: failure()
        run: cat server.log

      - name: Run tests with Allure
        run: |
          pytest --alluredir=allure-results

      # Генерируем отчет Allure из полученных результатов
      - name: Generate Allure Report
        run: |
          allure generate allure-results -o allure-report --clean

      # Загружаем отчет Allure как артефакт
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      # (Опционально) Загрузка HTML-отчета pytest-html, если он нужен
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.html
